FROM ubuntu

RUN apt-get update
RUN apt-get --assume-yes install software-properties-common

RUN add-apt-repository ppa:longsleep/golang-backports
RUN apt --assume-yes install golang-go

RUN add-apt-repository -y ppa:strukturag/libde265
RUN add-apt-repository -y ppa:strukturag/libheif
RUN add-apt-repository ppa:tonimelisma/ppa
RUN apt -y install libvips-dev

RUN mkdir /app
RUN mkdir /app/logs

ADD . /app

WORKDIR /app

RUN go mod tidy

RUN go build -o . main.go

CMD ["/app/main"]