version: "3.7"

services:
  img-resizer-api:
    container_name: img-resizer-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./public:/app/public
    ports:
      - "8000:8000"

volumes:
  public: